main: src.SpamX
name: SpamX
version: 1.2.3

commands:
   xreload:
      description: Reloads SpamX config file.
      usage: /xreload
      permission: SpamX.reload
      permission-message: You don't have permission.
   xoffense:
      description: Checks a players offense level.
      usage: /xoffense <player>
      permission: SpamX.checklevel
      permission-message: You don't have permission.
   xsetoffense:
      description: Sets a players offense level.
      usage: /xsetoffense <player> <number>
      permission: SpamX.setlevel
      permission-message: You don't have permission.

